version: '3'
services:
  zookeeper-prod:
    image: wurstmeister/zookeeper
    container_name: zookeeper-prod
    ports:
      - 2181:2181
  broker-prod-1:
    image: wurstmeister/kafka
    container_name: broker-prod-1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-prod
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-prod:2181'
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "zb-data:1:1,zb-events:1:1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.2:9092,PLAINTEXT_INTERNAL://broker-prod-1:29092
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://broker-prod-1:29092
    volumes:
       - ./data/kafka-data1/sock:/var/run/docker.sock
       - ./data/kafka-data1/data:/kafka
  node-prod:
    image: node:18.7
    container_name: node-prod
    depends_on:
      - broker-prod-1
    environment:
      DIRECCION: "broker-prod-1"
      PUERTO: "9092"
   #   NODE_ENV: production
    volumes:
   #    - ./:/home/node/app
       - ./data/node/producer:/home/node/app
    working_dir: /home/node/app
    command: "npm start"
  node-cons:
    image: node:18.7
    container_name: node-cons
    depends_on:
      - broker-prod-1
    environment:
      DIRECCION: "broker-prod-1"
      PUERTO: "9092"
      CLOUDID: "marseloaburto:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyQxOWM2ZWZlMWExOGU0MzcwOWViZDk3NjBiODRkM2NmYyRkNWM0MmVhNGQyYmE0OTU5OTZjNjA3OTMxODdmYWJlNQ=="
      USERNAME: "elastic"
      PASSWORD: "ZUM9PIgWeAPykSGjr46rzu30"
   #   NODE_ENV: production
    volumes:
   #    - ./:/home/node/app
       - ./data/node/consumer:/home/node/app
    working_dir: /home/node/app
    command: "npm start"
    restart: always